server:
  port: 8190

welcome:
  value: Version 2

account-service: http://account-service
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


#spring.cloud:
#    openfeign:
#      client:
#        config:
#          default:
#            readTimeout: 1000

resilience4j.circuitbreaker:
    instances:
      accountService:
        register-health-indicator: true
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        slidingWindowSize: 10
        minimumNumberOfCalls: 3
        failureRateThreshold: 50

management:
  endpoints:
    web:
      exposure:
        include: "*"